app_setting_name = "AccountActivationLink"
app_api_name = "-zuoraaccountsvc-api123"
env_value_all = "3"
env_value_dv2 = "10"
env_value_dv3 = None
env_value_ve2 = ""
env_value_hqe = None
env_value_qe3 = None
env_value_pre_e = "20"
env_value_pre_w = None
env_value_prd_e = None
env_value_prd_w = None
env_value = None # value should be 'dynamic' inorder to get the id of the app service should be fetched from the az portal
jira_ticket = 'XIOCLD-9629'
app_set_file_path = 'C:\\Users\\psharma\\PycharmProjects\\XioCloud\\testcase\\AppSetting.json'
template_dir = 'C:\\Users\\psharma\\PycharmProjects\\XioCloud\\lib\\templates\\'
device_view_model_file = 'C:\\Users\\psharma\\PycharmProjects\\XioCloud\\lib\\templates\\deviceviewmodel.json'
level1_abs_path = 'C:\\Users\\psharma\\PycharmProjects\\XioCloud\\testcase\\'
device_model_type = 'PC-350V-12'
git_branch = 'master'
git_branch_re = "'origin\/(.*)'"
git_pull_success_status = 'up to date'
git_cw_dir = 'C:\\Users\\psharma\\PycharmProjects\\XioCloud'
#repo_path = 'C:\\Users\\psharma\\Source\\Repos\\CrestronEngineering\\XIOCLOUD'
repo_path = 'C:\\Users\\psharma\\PycharmProjects\\XioCloud'